project:
  type: website

website:
  title: "bernoulli-euler-kommission"
  sidebar:
    style: "docked"
    border: true
    collapse-level: 4
    search: false
    contents:
      - section: "General"
        contents:
          - todo.qmd
      - section: "Euler"
        contents:
          - Euler.qmd
      - section: "Bernoulli"
        contents:
          - Bernoulli.qmd
format:
  html:
    theme: journal
    css: styles.css
    toc: true



